[project]
name = "invoice-parser"
version = "0.1.0"
description = "Invoice Parser using Prompt Engineering"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.93.2",
    "gradio>=4.0.0",
    "typing-extensions>=4.8.0",
] 